version: '3.8'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8001:8001"
      - "3003:3003"
    environment:
      - MYSQL_ROOT_PASSWORD=1010
      - MYSQL_DATABASE=stopify_soap
  db:
    container_name: db
    image: mysql
    restart: unless-stopped
    volumes:
      - ./migrate/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=1010
    ports:
      - "3306:3306"
